apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-convert-http-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-convert-http-demo
  template:
    metadata:
      labels:
        app: dubbo-convert-http-demo
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: '8081'
            - name: JVM_OPTS
              value: ENV_JVM_OPTS
          name: dubbo-convert-http-demo
          image: FULL_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: dubbo-convert-http-demo
  namespace: backend
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: dubbo-convert-http-demo
  selector:
    app: dubbo-convert-http-demo
  type: LoadBalancer
